# Generated by Django 4.0.3 on 2022-04-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=60)),
            ],
        ),
    ]
