# Generated by Django 4.0.3 on 2022-05-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default='2022-01-01')),
                ('dutycycle', models.IntegerField()),
                ('motorname', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
