# Generated by Django 4.0.3 on 2022-03-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
