# Generated by Django 4.0.3 on 2022-03-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_schedule_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='led_data',
            name='lednum',
            field=models.CharField(default=2022, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='led_data',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='led_data',
            name='timestamp',
            field=models.DateTimeField(default='2022-01-01'),
        ),
    ]
