# Generated by Django 4.0.3 on 2022-03-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_led_data_lednum_alter_led_data_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='led_data',
            old_name='lednum',
            new_name='ledname',
        ),
    ]
